// <auto-generated by .tmp/phase11/gen_catalog.py — Phase 11.2 curated catalog>
// Do not edit by hand; edit the generator and re-run it.
using System.Collections.Generic;
using WinForge.Core.Models;
using WinForge.Core.Services;

namespace WinForge.Infrastructure.ComponentIntelligence;

/// <summary>
/// Curated component catalog (Stages 11.1-11.2). Maps a SMALL set of
/// well-understood Windows components onto stable Microsoft package-family
/// identifiers. Technical targets use Prefix matching against well-known inbox
/// AppX family names (Microsoft-supported identifiers); a component only becomes
/// Curated when a discovered item actually matches. Unknown is preferred over
/// invented information. Each entry carries provenance (FACT vs RECOMMENDATION)
/// and, where relevant, scenario recommendation overrides.
/// </summary>
public sealed class CuratedComponentCatalog : IComponentCatalogProvider
{
    public IReadOnlyList<ComponentDefinition> GetDefinitions()
    {
        return new List<ComponentDefinition>
        {
            new ComponentDefinition
            {
                Id = "Weather",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Weather.DisplayName",
                ShortDescriptionKey = "Comp.Weather.Short",
                LongDescriptionKey = "Comp.Weather.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Weather.KeepIf" },
                RemoveIf = new[] { "Comp.Weather.RemoveIf" },
                KnownImpact = new[] { "Comp.Weather.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.BingWeather" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "weather" },
            },

            new ComponentDefinition
            {
                Id = "Clipchamp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Clipchamp.DisplayName",
                ShortDescriptionKey = "Comp.Clipchamp.Short",
                LongDescriptionKey = "Comp.Clipchamp.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Clipchamp.KeepIf" },
                RemoveIf = new[] { "Comp.Clipchamp.RemoveIf" },
                KnownImpact = new[] { "Comp.Clipchamp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Clipchamp.Clipchamp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "clipchamp" },
            },

            new ComponentDefinition
            {
                Id = "GetHelp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.GetHelp.DisplayName",
                ShortDescriptionKey = "Comp.GetHelp.Short",
                LongDescriptionKey = "Comp.GetHelp.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.GetHelp.KeepIf" },
                RemoveIf = new[] { "Comp.GetHelp.RemoveIf" },
                KnownImpact = new[] { "Comp.GetHelp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.GetHelp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "gethelp" },
            },

            new ComponentDefinition
            {
                Id = "XboxApp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.XboxApp.DisplayName",
                ShortDescriptionKey = "Comp.XboxApp.Short",
                LongDescriptionKey = "Comp.XboxApp.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Gaming, ComponentScenario.XboxGamePass },
                KeepIf = new[] { "Comp.XboxApp.KeepIf" },
                RemoveIf = new[] { "Comp.XboxApp.RemoveIf" },
                KnownImpact = new[] { "Comp.XboxApp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxApp" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxGamingOverlay" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxIdentityProvider" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxSpeechToTextOverlay" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxGameOverlay" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Xbox.TCUI" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.GamingServices" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.GamingServicesNet" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.GamingApp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.XboxApp.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "Xbox App" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.XboxApp.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new[] { new ScenarioRecommendation { Scenario = ComponentScenario.Gaming, Recommendation = RecommendationLevel.UsuallyKeep, ReasonKey = "Comp.XboxApp.Scen.Gaming" } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "xboxapp" },
            },

            new ComponentDefinition
            {
                Id = "DevHome",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.DevHome.DisplayName",
                ShortDescriptionKey = "Comp.DevHome.Short",
                LongDescriptionKey = "Comp.DevHome.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Developer },
                KeepIf = new[] { "Comp.DevHome.KeepIf" },
                RemoveIf = new[] { "Comp.DevHome.RemoveIf" },
                KnownImpact = new[] { "Comp.DevHome.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Windows.DevHome" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.DevHome.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new[] { new ScenarioRecommendation { Scenario = ComponentScenario.Developer, Recommendation = RecommendationLevel.UsuallyKeep, ReasonKey = "Comp.DevHome.Scen.Developer" } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "devhome" },
            },

            new ComponentDefinition
            {
                Id = "Photos",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Photos.DisplayName",
                ShortDescriptionKey = "Comp.Photos.Short",
                LongDescriptionKey = "Comp.Photos.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Photos.KeepIf" },
                RemoveIf = new[] { "Comp.Photos.RemoveIf" },
                KnownImpact = new[] { "Comp.Photos.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Windows.Photos" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "photos" },
            },

            new ComponentDefinition
            {
                Id = "FeedbackHub",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.FeedbackHub.DisplayName",
                ShortDescriptionKey = "Comp.FeedbackHub.Short",
                LongDescriptionKey = "Comp.FeedbackHub.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.FeedbackHub.KeepIf" },
                RemoveIf = new[] { "Comp.FeedbackHub.RemoveIf" },
                KnownImpact = new[] { "Comp.FeedbackHub.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsFeedbackHub" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "feedbackhub" },
            },

            new ComponentDefinition
            {
                Id = "Maps",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Maps.DisplayName",
                ShortDescriptionKey = "Comp.Maps.Short",
                LongDescriptionKey = "Comp.Maps.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.TouchPen, ComponentScenario.Laptop },
                KeepIf = new[] { "Comp.Maps.KeepIf" },
                RemoveIf = new[] { "Comp.Maps.RemoveIf" },
                KnownImpact = new[] { "Comp.Maps.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsMaps" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "maps" },
            },

            new ComponentDefinition
            {
                Id = "PhoneLink",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.PhoneLink.DisplayName",
                ShortDescriptionKey = "Comp.PhoneLink.Short",
                LongDescriptionKey = "Comp.PhoneLink.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Laptop, ComponentScenario.Bluetooth },
                KeepIf = new[] { "Comp.PhoneLink.KeepIf" },
                RemoveIf = new[] { "Comp.PhoneLink.RemoveIf" },
                KnownImpact = new[] { "Comp.PhoneLink.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.YourPhone" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "phonelink" },
            },

            new ComponentDefinition
            {
                Id = "Solitaire",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Solitaire.DisplayName",
                ShortDescriptionKey = "Comp.Solitaire.Short",
                LongDescriptionKey = "Comp.Solitaire.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Solitaire.KeepIf" },
                RemoveIf = new[] { "Comp.Solitaire.RemoveIf" },
                KnownImpact = new[] { "Comp.Solitaire.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.MicrosoftSolitaireCollection" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "solitaire" },
            },

            new ComponentDefinition
            {
                Id = "Teams",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Teams.DisplayName",
                ShortDescriptionKey = "Comp.Teams.Short",
                LongDescriptionKey = "Comp.Teams.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Office, ComponentScenario.EnterpriseDomain },
                KeepIf = new[] { "Comp.Teams.KeepIf" },
                RemoveIf = new[] { "Comp.Teams.RemoveIf" },
                KnownImpact = new[] { "Comp.Teams.Impact" },
                Dependencies = new[] { new ComponentDependency { ToId = "OneDrive", Relation = DependencyRelation.RelatedTo, Reason = "Teams stores shared chat files and attachments in OneDrive; the two are associated, but Teams core chat/calls/meetings work without OneDrive. This is NOT a hard runtime dependency." } },
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "MicrosoftTeams" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "teams" },
            },

            new ComponentDefinition
            {
                Id = "OneDrive",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.OneDrive.DisplayName",
                ShortDescriptionKey = "Comp.OneDrive.Short",
                LongDescriptionKey = "Comp.OneDrive.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Medium,
                Removal = RemovalSupport.Conditional,
                Restore = RestoreSupport.RequiresWindowsUpdate,
                UserScenarios = new[] { ComponentScenario.Office, ComponentScenario.Laptop },
                KeepIf = new[] { "Comp.OneDrive.KeepIf" },
                RemoveIf = new[] { "Comp.OneDrive.RemoveIf" },
                KnownImpact = new[] { "Comp.OneDrive.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.OneDriveSync" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new KnowledgeClaim[0],
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "onedrive" },
            },

            new ComponentDefinition
            {
                Id = "AV1VideoExtension",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.AV1VideoExtension.DisplayName",
                ShortDescriptionKey = "Comp.AV1VideoExtension.Short",
                LongDescriptionKey = "Comp.AV1VideoExtension.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.AV1VideoExtension.KeepIf" },
                RemoveIf = new[] { "Comp.AV1VideoExtension.RemoveIf" },
                KnownImpact = new[] { "Comp.AV1VideoExtension.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.AV1VideoExtension" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.AV1VideoExtension.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Store", Confidence = ConfidenceLevel.High, SourceReference = "AV1VideoExtension" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.AV1VideoExtension.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "av1videoextension" },
            },

            new ComponentDefinition
            {
                Id = "AVCEncoderVideoExtension",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.AVCEncoderVideoExtension.DisplayName",
                ShortDescriptionKey = "Comp.AVCEncoderVideoExtension.Short",
                LongDescriptionKey = "Comp.AVCEncoderVideoExtension.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.AVCEncoderVideoExtension.KeepIf" },
                RemoveIf = new[] { "Comp.AVCEncoderVideoExtension.RemoveIf" },
                KnownImpact = new[] { "Comp.AVCEncoderVideoExtension.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.AVCEncoderVideoExtension" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.AVCEncoderVideoExtension.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Store", Confidence = ConfidenceLevel.High, SourceReference = "AVCEncoderVideoExtension" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.AVCEncoderVideoExtension.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "avcencodervideoextension" },
            },

            new ComponentDefinition
            {
                Id = "BingNews",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.BingNews.DisplayName",
                ShortDescriptionKey = "Comp.BingNews.Short",
                LongDescriptionKey = "Comp.BingNews.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.BingNews.KeepIf" },
                RemoveIf = new[] { "Comp.BingNews.RemoveIf" },
                KnownImpact = new[] { "Comp.BingNews.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.BingNews" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.BingNews.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "BingNews" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.BingNews.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "bingnews" },
            },

            new ComponentDefinition
            {
                Id = "BingSearch",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.BingSearch.DisplayName",
                ShortDescriptionKey = "Comp.BingSearch.Short",
                LongDescriptionKey = "Comp.BingSearch.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.BingSearch.KeepIf" },
                RemoveIf = new[] { "Comp.BingSearch.RemoveIf" },
                KnownImpact = new[] { "Comp.BingSearch.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.BingSearch" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.BingSearch.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "BingSearch" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.BingSearch.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "bingsearch" },
            },

            new ComponentDefinition
            {
                Id = "Calculator",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Calculator.DisplayName",
                ShortDescriptionKey = "Comp.Calculator.Short",
                LongDescriptionKey = "Comp.Calculator.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Developer },
                KeepIf = new[] { "Comp.Calculator.KeepIf" },
                RemoveIf = new[] { "Comp.Calculator.RemoveIf" },
                KnownImpact = new[] { "Comp.Calculator.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsCalculator" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.Calculator.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "WindowsCalculator" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.Calculator.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "calculator" },
            },

            new ComponentDefinition
            {
                Id = "Notepad",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Notepad.DisplayName",
                ShortDescriptionKey = "Comp.Notepad.Short",
                LongDescriptionKey = "Comp.Notepad.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Developer },
                KeepIf = new[] { "Comp.Notepad.KeepIf" },
                RemoveIf = new[] { "Comp.Notepad.RemoveIf" },
                KnownImpact = new[] { "Comp.Notepad.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsNotepad" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.Notepad.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "WindowsNotepad" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.Notepad.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "notepad" },
            },

            new ComponentDefinition
            {
                Id = "Paint",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Paint.DisplayName",
                ShortDescriptionKey = "Comp.Paint.Short",
                LongDescriptionKey = "Comp.Paint.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Paint.KeepIf" },
                RemoveIf = new[] { "Comp.Paint.RemoveIf" },
                KnownImpact = new[] { "Comp.Paint.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Paint" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.Paint.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "Paint" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.Paint.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "paint" },
            },

            new ComponentDefinition
            {
                Id = "Terminal",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Terminal.DisplayName",
                ShortDescriptionKey = "Comp.Terminal.Short",
                LongDescriptionKey = "Comp.Terminal.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Developer },
                KeepIf = new[] { "Comp.Terminal.KeepIf" },
                RemoveIf = new[] { "Comp.Terminal.RemoveIf" },
                KnownImpact = new[] { "Comp.Terminal.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsTerminal" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.Terminal.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "WindowsTerminal" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.Terminal.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "terminal" },
            },

            new ComponentDefinition
            {
                Id = "ToDo",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.ToDo.DisplayName",
                ShortDescriptionKey = "Comp.ToDo.Short",
                LongDescriptionKey = "Comp.ToDo.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Office },
                KeepIf = new[] { "Comp.ToDo.KeepIf" },
                RemoveIf = new[] { "Comp.ToDo.RemoveIf" },
                KnownImpact = new[] { "Comp.ToDo.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Todos" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.ToDo.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "Todos" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.ToDo.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "todo" },
            },

            new ComponentDefinition
            {
                Id = "QuickAssist",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.QuickAssist.DisplayName",
                ShortDescriptionKey = "Comp.QuickAssist.Short",
                LongDescriptionKey = "Comp.QuickAssist.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.EnterpriseDomain, ComponentScenario.RemoteDesktop },
                KeepIf = new[] { "Comp.QuickAssist.KeepIf" },
                RemoveIf = new[] { "Comp.QuickAssist.RemoveIf" },
                KnownImpact = new[] { "Comp.QuickAssist.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.RemoteHelp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.QuickAssist.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "RemoteHelp" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.QuickAssist.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "quickassist" },
            },

            new ComponentDefinition
            {
                Id = "DesktopAppInstaller",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.DesktopAppInstaller.DisplayName",
                ShortDescriptionKey = "Comp.DesktopAppInstaller.Short",
                LongDescriptionKey = "Comp.DesktopAppInstaller.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Medium,
                Removal = RemovalSupport.Conditional,
                Restore = RestoreSupport.RequiresWindowsUpdate,
                UserScenarios = new[] { ComponentScenario.Developer },
                KeepIf = new[] { "Comp.DesktopAppInstaller.KeepIf" },
                RemoveIf = new[] { "Comp.DesktopAppInstaller.RemoveIf" },
                KnownImpact = new[] { "Comp.DesktopAppInstaller.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.DesktopAppInstaller" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                Provenance = new[] { new KnowledgeClaim { Kind = KnowledgeClaimKind.Fact, TextKey = "Comp.DesktopAppInstaller.Prov0", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.MicrosoftOfficial, SourceName = "Microsoft Learn", Confidence = ConfidenceLevel.High, SourceReference = "DesktopAppInstaller" } } }, new KnowledgeClaim { Kind = KnowledgeClaimKind.Recommendation, TextKey = "Comp.DesktopAppInstaller.Prov1", Sources = new[] { new KnowledgeSource { SourceType = KnowledgeSourceType.WinForgeCurated, SourceName = "WinForge review", Confidence = ConfidenceLevel.Verified } } } },
                ScenarioRecommendations = new ScenarioRecommendation[0],
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "desktopappinstaller" },
            },

        };
    }
}