// <auto-generated by .tmp/phase11/gen_catalog.py — Phase 11.1 curated catalog>
// Do not edit by hand; edit the generator and re-run it.
using System.Collections.Generic;
using WinForge.Core.Models;
using WinForge.Core.Services;

namespace WinForge.Infrastructure.ComponentIntelligence;

/// <summary>
/// Initial curated component catalog (Stage 11.1). Maps a SMALL set of
/// well-understood Windows components onto stable Microsoft package-family
/// identifiers. Technical targets use Prefix matching against well-known inbox
/// AppX family names (Microsoft-supported identifiers); a component only becomes
/// Curated when a discovered item actually matches. Unknown is preferred over
/// invented information — savings and many impact details are left Unknown.
/// </summary>
public sealed class CuratedComponentCatalog : IComponentCatalogProvider
{
    public IReadOnlyList<ComponentDefinition> GetDefinitions()
    {
        return new List<ComponentDefinition>
        {
            new ComponentDefinition
            {
                Id = "Weather",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Weather.DisplayName",
                ShortDescriptionKey = "Comp.Weather.Short",
                LongDescriptionKey = "Comp.Weather.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Weather.KeepIf" },
                RemoveIf = new[] { "Comp.Weather.RemoveIf" },
                KnownImpact = new[] { "Comp.Weather.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.BingWeather" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "weather" },
            },

            new ComponentDefinition
            {
                Id = "Clipchamp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Clipchamp.DisplayName",
                ShortDescriptionKey = "Comp.Clipchamp.Short",
                LongDescriptionKey = "Comp.Clipchamp.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Clipchamp.KeepIf" },
                RemoveIf = new[] { "Comp.Clipchamp.RemoveIf" },
                KnownImpact = new[] { "Comp.Clipchamp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Clipchamp.Clipchamp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "clipchamp" },
            },

            new ComponentDefinition
            {
                Id = "GetHelp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.GetHelp.DisplayName",
                ShortDescriptionKey = "Comp.GetHelp.Short",
                LongDescriptionKey = "Comp.GetHelp.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.GetHelp.KeepIf" },
                RemoveIf = new[] { "Comp.GetHelp.RemoveIf" },
                KnownImpact = new[] { "Comp.GetHelp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.GetHelp" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "gethelp" },
            },

            new ComponentDefinition
            {
                Id = "XboxApp",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.XboxApp.DisplayName",
                ShortDescriptionKey = "Comp.XboxApp.Short",
                LongDescriptionKey = "Comp.XboxApp.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Gaming, ComponentScenario.XboxGamePass },
                KeepIf = new[] { "Comp.XboxApp.KeepIf" },
                RemoveIf = new[] { "Comp.XboxApp.RemoveIf" },
                KnownImpact = new[] { "Comp.XboxApp.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxApp" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxGamingOverlay" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxIdentityProvider" }, new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.XboxSpeechToTextOverlay" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "xboxapp" },
            },

            new ComponentDefinition
            {
                Id = "Photos",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Photos.DisplayName",
                ShortDescriptionKey = "Comp.Photos.Short",
                LongDescriptionKey = "Comp.Photos.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Photos.KeepIf" },
                RemoveIf = new[] { "Comp.Photos.RemoveIf" },
                KnownImpact = new[] { "Comp.Photos.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.Windows.Photos" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "photos" },
            },

            new ComponentDefinition
            {
                Id = "FeedbackHub",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.FeedbackHub.DisplayName",
                ShortDescriptionKey = "Comp.FeedbackHub.Short",
                LongDescriptionKey = "Comp.FeedbackHub.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.FeedbackHub.KeepIf" },
                RemoveIf = new[] { "Comp.FeedbackHub.RemoveIf" },
                KnownImpact = new[] { "Comp.FeedbackHub.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsFeedbackHub" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "feedbackhub" },
            },

            new ComponentDefinition
            {
                Id = "Maps",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Maps.DisplayName",
                ShortDescriptionKey = "Comp.Maps.Short",
                LongDescriptionKey = "Comp.Maps.Long",
                Recommendation = RecommendationLevel.RecommendedRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.TouchPen, ComponentScenario.Laptop },
                KeepIf = new[] { "Comp.Maps.KeepIf" },
                RemoveIf = new[] { "Comp.Maps.RemoveIf" },
                KnownImpact = new[] { "Comp.Maps.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.WindowsMaps" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "maps" },
            },

            new ComponentDefinition
            {
                Id = "PhoneLink",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.PhoneLink.DisplayName",
                ShortDescriptionKey = "Comp.PhoneLink.Short",
                LongDescriptionKey = "Comp.PhoneLink.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Laptop, ComponentScenario.Bluetooth },
                KeepIf = new[] { "Comp.PhoneLink.KeepIf" },
                RemoveIf = new[] { "Comp.PhoneLink.RemoveIf" },
                KnownImpact = new[] { "Comp.PhoneLink.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.YourPhone" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "phonelink" },
            },

            new ComponentDefinition
            {
                Id = "Solitaire",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Solitaire.DisplayName",
                ShortDescriptionKey = "Comp.Solitaire.Short",
                LongDescriptionKey = "Comp.Solitaire.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new ComponentScenario[0],
                KeepIf = new[] { "Comp.Solitaire.KeepIf" },
                RemoveIf = new[] { "Comp.Solitaire.RemoveIf" },
                KnownImpact = new[] { "Comp.Solitaire.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.MicrosoftSolitaireCollection" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "solitaire" },
            },

            new ComponentDefinition
            {
                Id = "Teams",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.Teams.DisplayName",
                ShortDescriptionKey = "Comp.Teams.Short",
                LongDescriptionKey = "Comp.Teams.Long",
                Recommendation = RecommendationLevel.OptionalRemove,
                Risk = RiskLevel.Low,
                Removal = RemovalSupport.Supported,
                Restore = RestoreSupport.Easy,
                UserScenarios = new[] { ComponentScenario.Office, ComponentScenario.EnterpriseDomain },
                KeepIf = new[] { "Comp.Teams.KeepIf" },
                RemoveIf = new[] { "Comp.Teams.RemoveIf" },
                KnownImpact = new[] { "Comp.Teams.Impact" },
                Dependencies = new[] { new ComponentDependency { ToId = "OneDrive", Relation = DependencyRelation.RelatedTo, Reason = "Teams stores shared chat files and attachments in OneDrive; the two are associated, but Teams core chat/calls/meetings work without OneDrive. This is NOT a hard runtime dependency." } },
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "MicrosoftTeams" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "teams" },
            },

            new ComponentDefinition
            {
                Id = "OneDrive",
                Category = ComponentCategory.AppX,
                DisplayNameKey = "Comp.OneDrive.DisplayName",
                ShortDescriptionKey = "Comp.OneDrive.Short",
                LongDescriptionKey = "Comp.OneDrive.Long",
                Recommendation = RecommendationLevel.UsuallyKeep,
                Risk = RiskLevel.Medium,
                Removal = RemovalSupport.Conditional,
                Restore = RestoreSupport.RequiresWindowsUpdate,
                UserScenarios = new[] { ComponentScenario.Office, ComponentScenario.Laptop },
                KeepIf = new[] { "Comp.OneDrive.KeepIf" },
                RemoveIf = new[] { "Comp.OneDrive.RemoveIf" },
                KnownImpact = new[] { "Comp.OneDrive.Impact" },
                Dependencies = new ComponentDependency[0],
                Conflicts = new string[0],
                TechnicalTargets = new[] { new TechnicalTarget { Category = ComponentCategory.AppX, Match = MatchMethod.Prefix, Pattern = "Microsoft.OneDriveSync" } },
                CompatibilityRules = new[] { new CompatibilityRule
                {
                    SupportedBuildMin = "22000",
                    KnownOnBuilds = new[] { "26100" }
                } },
                EstimatedSavingsBytes = 0,
                SavingsConfidence = SavingsConfidence.None,
                Tags = new[] { "onedrive" },
            },

        };
    }
}